version: '3'

services:
  postgres:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ${PWD}/fixture.postgres.sql:/fixture.sql
  nginx:
    image: nginx:1.17.5-alpine
    volumes:
      - media:/usr/share/nginx/html
      - ${PWD}/data/announcements:/usr/share/nginx/html/announcements
      - ${PWD}/data/questions:/usr/share/nginx/html/questions
    ports:
      - 8080:80
  kobra:
    image: kolibreorg/kobra:latest
    environment:
      - SECRET_KEY=yourOwnSecretKey
      - STORAGE_PATH=/srv/media
      - DATABASE_URL=postgres://postgres:password@postgres:5432/kobra
      - WAIT_FOR=tcp://postgres:5432
    volumes:
      - media:/srv/media
    ports:
      - 3000:3000
    depends_on:
      - postgres
  kados-v1:
    image: kolibreorg/kados:0.1.3-php7.2
    environment:
      - DODP_SUPPORTED_OPTIONAL_OPERATIONS_SERVICE_PDTB2_KEY_PROVISION=0 # Not supported in kados
    ports:
      - 8081:80
    depends_on:
      - kobra
  kados-v2:
    image: kolibreorg/kados:0.2.4-php7.2
    environment:
      - DODP_SUPPORTED_OPTIONAL_OPERATIONS_SERVICE_PDTB2_KEY_PROVISION=0 # Not supported in kados
      - DODP_SUPPORTED_OPTIONAL_OPERATIONS_SERVICE_TERMS_OF_SERVICE=0 # Not support in kobra
      - DODP_SUPPORTED_OPTIONAL_OPERATIONS_SERVICE_USER_CREDENTIALS=0 # Now supported in kados
    ports:
      - 8082:80
    depends_on:
      - kobra

volumes:
  media:
